### ISSUE TITLE
POST(create) operation should post to a collection URI

### ISSUE THREAD

**Issue by karthik-sethuraman** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#107]
It is a typical RESTful best-practice to POST/create to a collection/list URI rather than have the client specify an ID in the POST URI. This allows for the API provider to create the object instance and assign an instance ID. This URI of the created object (including ID) can be specified as the "location" http-header attribute. The created object instance can be returned in the body of the response.

**Comment by rvilalta** [comment]
Fixed in #121
