### ISSUE TITLE
NodeEdgePoint type in swagger files has different definitions

### ISSUE THREAD

**Issue by burnout171** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#108]
We observed a different Tapi NodeEdgePoint definition in swagger files. 
For example NodeEdgePoint in TapiTopology.swagger has direction enum with predefined values,
but in TapiVirtualNetwork.swagger and TapiOdu.swagger files direction enum is missing. 
We did not check other file files.

**Comment by rvilalta** [comment]
This is due to a bug in the swagger plugin.

**Comment by rvilalta** [comment]
Fixed in #117
