### ISSUE TITLE
ServiceEndPoint type in swagger files has different definitions 

### ISSUE THREAD

**Issue by burnout171** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#109]
We observed a different Tapi ServiceEndPoint definition in swagger files. 
For example ServiceEndPoint in Tapi.swagger has direction enum with predefined values,
but in TapiVirtualNetwork.swagger and TapiPathComputation.swagger files direction enum is missing. 
We did not check other file files.

**Comment by rvilalta** [comment]
Fixing

**Comment by rvilalta** [comment]
Fixed in #117
