### ISSUE TITLE
Different files contain a lot of the same objects.

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#112]
Hello!

I would like to add more details for the problem created by Pavel Likin: https://github.com/OpenNetworkingFoundation/Snowmass-ONFOpenTransport/issues/110

The problem described in the request number: 110 , contains in different files.
For example: 
1) Tapi.swagger : ServiceEndPoint and _serviceEndPointSchema;
2) TapiTopology.swagger : Topology and _topologySchema;
3) TapiConnectivity.swagger : Connection and _connectionSchema;
4) TapiConnectivity.swagger : ConnectivityService and _connectivityServiceSchema;
5) TapiNotification.swagger : NotificationSubscriptionService and _notifSubscriptionSchema;
6) TapiNotification.swagger : Notification and _notificationSchema;
7) TapiPathComputation.swagger : Path and _pathSchema;
8) TapiPathComputation.swagger : PathComputationService and _pathCompServiceSchema;
9) TapiVirtualNetwork.swagger : VirtualNetworkService and _vnwServiceSchema;

Please check it. 

Thank you!

**Comment by rvilalta** [comment]
5) TapiNotification.swagger : NotificationSubscriptionService and _notifSubscriptionSchema;

Are different objects.

**Comment by rvilalta** [comment]
Fixed in #117
