### ISSUE TITLE
Swagger Error. Different swagger files contain "Swagger Error"

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#113]
Hello!

Different swagger files contain "Swagger Error".
Please check files: Tapi.swagger, TapiConnectivity.swagger, TapiPathComputation.swagger, TapiVirtualNetwork.swagger.

![swagger_error](https://cloud.githubusercontent.com/assets/13441097/19228343/f6ad843e-8ecc-11e6-97b6-02634703108e.PNG)

**Comment by rvilalta** [comment]
Fixed in pull request #117
