### ISSUE TITLE
Swagger Code Generator Error.

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#114]
Please check all swagger files for Code Generator Errors.
We tested TapiTopology.swagger Code Generator for Client -> Java. 
And we catch an error:

![swagger_error_2](https://cloud.githubusercontent.com/assets/13441097/19228599/894bf698-8ecf-11e6-8391-4f040cf56efa.png)

![swagger_error_3](https://cloud.githubusercontent.com/assets/13441097/19228602/8eab93f0-8ecf-11e6-814a-53dfa3a228c6.png)

**Comment by rvilalta** [comment]
The swagger files are compliant but Codegen does not understand keyword AllOf.
Inherited class parameters need to be added and AllOf removed.
