### ISSUE TITLE
Return of yang list should be in the JSON form 

### ISSUE THREAD

**Issue by rvilalta** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#118]
Expected output:
{ "itemlist" : [ ref1, ...] }

**Comment by NikolayKolyada** [comment]
Hello!
We created itemlist object for support this functionality in our controller. 
Example:
Request: GET http://<ip>:<port>/restconf/config/Context/_topology/
Response: 
```
{
  "itemlist": [
    "/restconf/config/Context/_topology/top0/"
  ]
}
```
Is the controller's answer correct?
OR
Do we need create response with only object uuid(top0) without full URL(/restconf/config/Context/_topology/) ? 

Thank you!

**Comment by rvilalta** [comment]
Yes the answer is correct. I opened this issue to update swagger definitions.
