### ISSUE TITLE
Protection path for ConnectivityService

### ISSUE THREAD

**Issue by burnout171** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#137]
Hello,

Unfortunately from the TAPI description I did not find the possibility to create a protection path for ConnectivityService.
Could TAPI community throw a light on the mentioned issue?

**Comment by RodLU** [comment]
Protection use cases are in progress in ONF. And then will deal with protection issue of ConnectivityService.

**Comment by karthik-sethuraman** [comment]
@RodLU is right. Explicit control of protection/restoration is under discussion and scheduled for next major release.

**Comment by burnout171** [comment]
@RodLU, @karthik-sethuraman thank you for explanation. Could you please share a possible date of a new TAPI major release?

**Comment by karthik-sethuraman** [comment]
The TAPI Resilience feature draft is now part 2.0
