### ISSUE TITLE
Request to add /operations/getConnectionList/ for RPC calls.

### ISSUE THREAD

**Issue by burnout171** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#138]
Hello,

It is possible to get Connection List from Restconf `/config/Context/_connection/` URL.
What to you think about to add `/operations/getConnectionList/` URL for RPC calls for consistency?
All mentioned entities are described in TapiConnectivity.swagger file.

**Comment by rvilalta** [comment]
Karthik, what do you think? It is an easy request.

**Comment by rvilalta** [comment]
@karthik-sethuraman

**Comment by karthik-sethuraman** [comment]
Yes. We can add this in 1.0.2

**Comment by shikhmanter** [comment]
So today, when giving an explicit path, we should create new TeLink objects and fill the path of the node and the nodeEdgePoint?
