### ISSUE TITLE
new ConnectivityService provisioning question

### ISSUE THREAD

**Issue by shikhmanter** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#142]
When creating new ConnectivityService, two ConnectivityServicePort should be also created and mapped to NodeEdgePoint objects.
How can the model be updated with this new mapping?
I was trying to use the POST API of "/operations/getNodeEdgePointDetails/" which expects GetNodeEdgePointDetailsRPCInputSchema as an input.
GetNodeEdgePointDetailsRPCInputSchema holds only strings and no NodeEdgePoint object...

**Comment by rvilalta** [comment]
I do not recomend usage of RPCs and stick only to REST. 

To create a ConnectivityService you only need to populate ConnectivityServicePorts with references to the ServiceEndPoints.
ServiceEndPoints references might be retrieved using:
GET /config/Context/_serviceEndPoint/ (Tapi.yang)

In TapiTopology.yang, you can find inside _node/_ownedNodeEdgePoint/_mappedServiceEndPoint the correspondence of the nodeEdgePoint with a ServiceEndPoint (if any).

Hope I made myself clear.

**Comment by shikhmanter** [comment]
So the model will update automatically with the new mapping of ConnectivityServicePort/NodeEdgePoint?

**Comment by rvilalta** [comment]
Yes, the server should update that.

**Comment by karthik-sethuraman** [comment]
@shikhmanter 
To answer the original question, the goal of having an ServiceEndPoint is to enable requesting ConnectivityService without mandating knowledge of Topology (NEP). But (as explained by @rvilalta) the topological construct NEP has a reference to its mapped ServiceEndPoints (which is maintained by the provider).
So there is no direct mapping between a ConnectivityServicePort and a NodeEdgePoint,but only to the ServiceEndPoint.

**Comment by karthik-sethuraman** [comment]
#149
