### ISSUE TITLE
_corouteInclusion object in Connectivity Constraint

### ISSUE THREAD

**Issue by rvilalta** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#143]

**Comment by italobusi** [comment]
@rvilalta : could you please provide some description of this new object? A reference to some document could be sufficient for the time being.
Thanks, Italo

**Comment by rvilalta** [comment]
This appears from the analyzed use cases in the TID setup. The intention is to provide co-routing, as it was not expected in the T-API, while exclusion was expected.
