### ISSUE TITLE
Loss of integrity between objects such as ServiceEndPoint and NodeEdgePoint

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#149]
Hello!

We find loss of integrity between objects such as ServiceEndPoint and NodeEdgePoint.

Problem description:

In previous versions:
ServiceEndPoint using in "servicePort" for ConnectivityService creation. And ServiceEndPoint contained "_mappedNodeEdgePoint" with link to NodeEdgePoint in previous versions of TAPI. 

But in last version:
Only NodeEdgePoint contain "_mappedServiceEndPoint" with link to ServiceEndPoint. And ServiceEndPoint not contain any information about NodeEdgePoint. 

For ConnectivityService creation we using ServiceEndPoint, but ServiceEndPoint not contain information about NodeEdgePoint. We lost the direct link between objects. It seems that now we should iterate through the whole array of NodeEdgePoint's to find the one with correct "_mappedServiceEndPoint".

Is our understanding correct? Or it is bag ?

Thanks a lot!

**Comment by karthik-sethuraman** [comment]
Initially when TAPI was one monolith module, we could afford to have many inter-dependency relationships. But after modularizing TAPI,  it became necessary to revisit the navigability of some of these relationships.

In this case, the ServiceEndPoints are used by all TAPI modules - Connectivity, Path, VirtualNetwork, etc. A TAPI Context (a container for TAPI provider-client interaction) is in fact defined by the set of ServiceEndPoints. Therefore the ServiceEndPoint appears in the base/common Tapi module.

But to avoid an dependency of the common Tapi module on TapiTopology module (which contains NodeEdgePoint), it became necessary to reverse the navigability of the SEP-NEP relationship.

Conceptually too, it is required that simple TAPI clients can operate on the interface in a intent-like manner, just dealing with SEPs and not requiring knowledge of Topology (e.g. request Connectivity between SEPs)

**Comment by NikolayKolyada** [comment]
We see sequence of operations in the system:
1)NEP contain link to SEP in "_mappedServiceEndPoint".
2)In request to create ConnectivityService SEP is used. 
3)For handling it request controller needs to iterate through the whole array of NEP's to find the one with correct "_mappedServiceEndPoint".
4)Only after that controller can compute path for ConnectivityService request.

For example: if controller topology contain large number of NEP, so controller spend a lot of time for operation of find concrete NEP with correct SEP. It is bottle neck situation, we loss of performance.

**Comment by karthik-sethuraman** [comment]
@NikolayKolyada 
>> 3)For handling it request controller needs to iterate through the whole array of NEP's to find the one with correct "_mappedServiceEndPoint".

The mapping between SEP and NEP is specified/maintained by the TAPI provider. Therefore it is expected that the provider maintains this mapping in a more suitable form for processing - e.g. an hashmap indexed by SEP and/or NEP ids.
Please note that TAPI schema is just an interface schema, i.e. represents what gets sent over the wire, not necessarily the provider or client's internal implementation schema. For e.g., a TAPI provider may use an graph database schema which is more conducive to traversing relationships.
