### ISSUE TITLE
Clarification regarding "_corouteInclusion" constraint model

### ISSUE THREAD

**Issue by antoniofelix** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#159]
The new "_corouteInclusion" constraint (connectivityService) is defined as a leaf-list of connectivityService uuid. This seems to indicate that it would be possible to request a connectivityService that is corouted to a given set of existing connectivityServices. The question is how to interpret the use case:

1) Should the new service be corouted to all services in the set? This might not be feasible since the services in the set might not share the same route... 

2) Should the new service be corouted to one of the services in the set? 

Probably it would be better to have the "_corouteInclusion" as a "leaf" instead of a "leaf-list". The orchestrator would have to indicate the exact connectivityService to which the new service should be corouted.

**Comment by karthik-sethuraman** [comment]
I would tend to agree to define it as a leaf.

**Comment by karthik-sethuraman** [comment]
Fixed by #173
