### ISSUE TITLE
Different between YANG and SWAGGER for UUID.

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#160]
We found different between YANG and SWAGGER for UUID definition. 
For example: 
In Tapi.yang:
```
grouping GlobalClass {
            leaf uuid {
                type UniversalId;
                description "UUID: An identifier that is universally unique
                    (consider in the context of Identifier: A property of an entity/role with a value that is unique within an identifier space, where the identifier space is itself globally unique, and immutable. An identifier carries no semantics with respect to the purpose or state of the entity)";
            }


typedef UniversalId {
            type string {
                pattern '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}';
            }
```

In Tapi.swagger: 
```
"GlobalClass": {

            "properties": {
                    "uuid": {
                            "type": "string",
                            "description": "UUID: An identifier that is universally unique\n(consider in the context of Identifier: A property of an entity/role with a value that is unique within an identifier space, where the identifier space is itself globally unique, and immutable. An identifier carries no semantics with respect to the purpose or state of the entity)"
                        },
```

UUID from YANG - type UniversalId with pattern.

UUID from SWAGGER - "type": "string" without any patterns.

We do not understand what type to choose for UUID.

Could you please check this problem and define correct definition for UUID.

**Comment by karthik-sethuraman** [comment]
Need to update the YANG definition to match the swagger.

**Comment by NikolayKolyada** [comment]
@karthik-sethuraman , You wrote that: "Need to update the YANG definition to match the swagger.", but in last commit we detected opposite behavior with copy YANG definition in to swagger. 
My questions:
1) Is it correct? Is it last UUID change?
2) Do we need use UUID with Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}?

**Comment by karthik-sethuraman** [comment]
Yes. I mis-spoke earlier. The main goal is to make them consistent. Since the yang text represents the correct standardized one (from RFC4122) for the UniversalId data-type, while the swagger text just copied the  attribute description and not the data-type format, the current commits are the correct behavior.

**Comment by NikolayKolyada** [comment]
@karthik-sethuraman , Thank you! I understood.
