### ISSUE TITLE
ConnectionEndPoint and _clientNodeEdgePoint/_serverNodeEdgePoint

### ISSUE THREAD

**Issue by shikhmanter** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#162]
While working on a Service connection, got a doubt.
ServiceConnectivity owns a Connection. A Connection owns ConnectionEndPoint.
A ConnectionEndPoint as the following two properties: _clientNodeEdgePoint and _serverNodeEdgePoint
 
What is the use/difference of the two?

@karthik-sethuraman

**Comment by karthik-sethuraman** [comment]
![image](https://cloud.githubusercontent.com/assets/1877698/20360682/a714c6f0-ac02-11e6-9e78-d9cd79c9b1bc.png)

W.R.T the figure about, in a multi-layer network stack, a ConnectionEndPoint (and associated connection) in a given layer (e.g. ODU) is supported by the NodeEdgePoint (and the associated Link) at that layer. This relationship is captured via the _serverNodeEdgePoint property. At the same time, this connection (and associated ConnectionEndPoint) and its associated trail could support client-layer Links (and client-layer NodeEdgePoints). This relationship is captured via the _clientNodeEdgePoint property.
