### ISSUE TITLE
TapiTopology.uml  in definition of "Node", "_encapTopology" should be "shared"

### ISSUE THREAD

**Issue by zgysc** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#188]
In line 326,  the attribute's value of "aggregation" for the "_encapTopology" should be "shared". When using "composite", it will cause endless loop in the Swagger editor because "Topology" also has a property named "_node" whose aggregation value is "composite".

**Comment by zgysc** [comment]
aggregation="composite"  need to be change to "shared"

**Comment by zgysc** [comment]
@daviderickson @capveg @dtalayco @jean2  , Hi guys, could you please check it?

**Comment by RodLU** [comment]
The "_encapTopology" of Node is set by PassedByReference in the Profile in UML Model. When it is mapped to YANG model, the "_encapTopology" attribute will be passed by reference in grouping Node, which is 'typeref' to Topology UUID in YANG files.

**Comment by zgysc** [comment]
Thank you
