### ISSUE TITLE
ConnectivityServicePort and ServiceEndPoint operations

### ISSUE THREAD

**Issue by jtpugac** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#195]
Currently TAPI does not support operations on ConnectivityServicePort and ServiceEndPoint.  The MEF NRP project is using TAPI and has a need to augment attributes on a ConnectivityServicePort and likely ServiceEndPoint. An example of this would be a dynamic bandwidth profile change based on a upstream customer request.  A bandwidth profile can exist on the ConnectivityServicePort and ServiceEndPoint.

**Comment by karthik-sethuraman** [comment]
This was addressed as part of #199, #200
