### ISSUE TITLE
Renaming ServiceEndPoint

### ISSUE THREAD

**Issue by jtpugac** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#197]
The term ServiceEndPoint in TAPI model has created confusion when used by other API implementations.  Specifically, TAPI is being used in the MEF NRP (Network Resource Provisioning) API effort and given this is at the network resource layer, the term is causing concern. Therefore MEF NRM/NRP projects would like to propose the following changes:
ServiceEndPoint --> ServiceInterfacePoint
ConnectivityServicePort --> ConnectivityServiceEndPoint

**Comment by karthik-sethuraman** [comment]
Additionally the following classes should be renamed for consistency
PathServicePort --> PathServiceEndPoint
VirtualNetworkServicePort --> VirtualNetworkServiceEndPoint
