### ISSUE TITLE
Add Capacity Attribute to the ServiceInterfacePoint(ServiceEndPoint)

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#199]
With the capacity attribute in ServiceInterfacePoint the client can know how much capacity is available from the SEPs before creating a connectivity-service, and can know the total capacity when intend to optimize the traffics.
It is proposal to add the transferCapacityPac to the ServiceInterfacePoint. 
It is proposal to keep _totalPotentialCapacity_ and _availableCapacity_, at transferCapacityPac , and remove the _capacityAssignedToUserView_ and _capacityInteractionAlgorithm_.

**Comment by italobusi** [comment]
I agree to remove the capacityAssignedToUserView and capacityInteractionAlgorithm.

**Comment by karthik-sethuraman** [comment]
**_TAPI Call 6/6/2017:  Agreed_** - It was also noted that this issue and related use cases is described in the ONF contribution onf2017.037.xx and was presented/discussed at the ONF Frankfurt interim meeting (Feb 2017) as well as subsequent TAPI calls. As a result of those discussions, the group agreed to add the Capacity attribute to ServiceInterfacePoint  and ServiceEndPoint,  but not clear if there is value to add the attribute to the NodeEdgePoint.
