### ISSUE TITLE
Enhance ConnectivityServiceEndPoint to include capacity/bandwidth

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#200]
Enhance ConnectivityServiceEndPoint to include capacity/bandwidth (to support different input and output B/W profiles).
Do we need same attribute in the ConnectivityConstraint? If so, how to resolve in-consistencies if present.

**Comment by karthik-sethuraman** [comment]
**_TAPI Call 6/6/2017:  Agreed_** - It was also noted that this issue and related use cases are described in the ONF contribution onf2017.037.xx which was presented/discussed at the ONF Heidelberg interim meeting (Feb 2017) as well as subsequent TAPI calls. As a result of those discussions, the group agreed to add the Capacity attribute to **ServiceInterfacePoint**  and **ConnectivityServiceEndPoint**,  but not clear if there is value to add the attribute to the **NodeEdgePoint**.
