### ISSUE TITLE
Change the type of the ConnectivityServiceEndPoint layerProtocol

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#201]
To support technology specific attributes for the ConnectivityServiceEndPoint, it is proposed to change the type of the layerProtocol attribute of ConnectivityServiceEndPoint from LayerProtocolName to LayerProtocol.

**Comment by italobusi** [comment]
It would be worthwhile having the description of some use cases and/or examples where we need to configure layerProtocol technology-specific attributes

**Comment by karthik-sethuraman** [comment]
**_TAPI Call 6/6/2017:  Agreed_** - It was also noted that this issue and related use cases are described in the ONF contribution onf2017.037.xx which was presented/discussed at the ONF Heidelberg interim meeting (Feb 2017) as well as subsequent TAPI calls. As a result of those discussions, the group agreed to add the LayerProtocol attribute to the **ConnectivityServiceEndPoint** to enable specification of layer-specific information in the _ConnectivityService_ request.
