### ISSUE TITLE
Redundant TerminationDirection of ServiceInterfacePoint

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#215]
There is a direction attribute in the SIP with TerminationDirection datatype. There is also a terminationDirection attribute in the LayerProtocol of SIP. I think the Direction attribute of SIP is redundant. What if the TerminationDirections are different in different LayerProtocols in a SIP, how can we define the direction attribute in this SIP?

**Comment by karthik-sethuraman** [comment]
Agree. This is also applicable to the NodeEdgePoint and ConnectionEndPoint classes.

**Comment by karthik-sethuraman** [comment]
TAPI Call 6/6/2017:  Agreed
