### ISSUE TITLE
TerminationDirection/State of LayerProtocol in SIP should be OPTIONAL

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#216]
Since the ServiceInterfacePont is a logical point which is mapped with the NodeEdgePont for the purpose of decoupling topology and connectivity, the SIP doesn't actually terminate the LP, I think we should make the TerminationDirection/State of LayerProtocol in SIP OPTIONAL, maybe by modify the multiplicity or profile, I'm not sure.

**Comment by karthik-sethuraman** [comment]
This issue is fed in the pull request #256 as SIP now does not include the entire LayerProtocol, but just the LayerProtocol name
