### ISSUE TITLE
Data type of totalSize in Capacity

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#227]
The data type of totalSize is enumeration named FixedCapacityValue. It's found that the FixedCapacityValue can't cover all the rates that need to be present. It's proposed to change the data type into Integer with unit of Mbps in the description.

**Comment by karthik-sethuraman** [comment]
Agreed on TAPI Call  06/27/2017 with the enhancement that FixedCapacityValue is a complex datatype with  two attributes - an integer value and unit enumeration {GBPS, MBPS, KBPS}
