### ISSUE TITLE
Issues of Path of TapiPathComputation

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#229]
It is noticed that the _path of PathComputationContext is passed by reference and _path of PathComputationService is passed by value in UML model. But in the YANG model, this is reversed. It's also noticed that there is no interface to retrieve the Path that has been computed.

**Comment by karthik-sethuraman** [comment]
#161

**Comment by karthik-sethuraman** [comment]
Fixed in pull request #257
