### ISSUE TITLE
Proposal to add AdminStatePac to ConnectivityServiceEndPoint and ServiceInterfacePoint

### ISSUE THREAD

**Issue by jtpugac** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#233]
[TAPI and MEF NRP State Machine Alignment.docx](https://github.com/OpenNetworkingFoundation/Snowmass-ONFOpenTransport/files/1109533/TAPI.and.MEF.NRP.State.Machine.Alignment.docx)

**Comment by karthik-sethuraman** [comment]
This issue was discussed in the TAPI call on 06/27 and it was agreed to enhance the state attributes for the SIP and CSEP as proposed. Separate related issue is #195 that proposes SIP/CSEP update operations.
