### ISSUE TITLE
termination-pac or termination-spec ?

### ISSUE THREAD

**Issue by miguelborges99** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#248]
The yang files tapi-och.yang and tapi-eth, define in the "connection-end-point-lp-spec" group two containers named as "adapter-spec" and "termination-spec". However, in yang file tapi-odu.yang, the equivalent group - "odu-connection-end-point-lp-spec" - adopts a different naming for the containers, i.e. "adapter-pac" and "termination-pac".  Can you harmonize this?

**Comment by italobusi** [comment]
It looks like the OCh Spec model is using an old naming convention. The latest naming convention I am aware of are the one used in the UML ODU Spec:
- OduConnectionEndPointLpSpec
- OduCtpPac
- OduTerminationPac
- OduClientAdaptationPac

@karthik-sethuraman : please confirm if there has been any change on the naming convention

I do not know why the names of the YANG containers do not fully correspond with the names of the UML object classes

**Comment by bzeuner** [comment]
Here the UML classes to assist the discussion:

![greenshot](https://user-images.githubusercontent.com/6310277/29175744-2d0919f0-7dea-11e7-959f-24947b36a37b.png)

**Comment by bzeuner** [comment]
@italobusi : The names of the YANG containers correspond to the names of the object classes:

![greenshot](https://user-images.githubusercontent.com/6310277/29176089-28e030ec-7deb-11e7-99f0-af40d3ccb57a.png)

**Comment by bzeuner** [comment]
@italobusi : Sorry, I meant "The names of the YANG containers correspond to the names of the **attributes** (navigable association ends)."

**Comment by italobusi** [comment]
@bzeuner : thanks for the clarification about the correspondence between the YANG container and grouping names and the UML attributes and object class names.

**Comment by italobusi** [comment]
As far as I have understood the outcome of the discussion on the naming convention, it is the OCh Spec model that needs to be updated to align with the naming convention of the ODU Spec model

@karthik-sethuraman : please confirm/correct my understanding

**Comment by karthik-sethuraman** [comment]
@italobusi : Yes that is correct. We have to update the OCH spec to follow the ODU spec naming  conventions.

**Comment by miguelborges99** [comment]
I think you need to do the same for the ETH spec.

**Comment by italobusi** [comment]
I think the whole ETH spec requires major reworking but I agree that it also needs to follow the same naming conventions.

**Comment by karthik-sethuraman** [comment]
Fixed in the pull request #256
