### ISSUE TITLE
Module name in leafref path

### ISSUE THREAD

**Issue by HuiDingCATR** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#80]
Hi Karthik,

Should the path use the class's module name? Take the line 116-122 in TapiTopology.yang for example. The path uses "Tapi" before "uuid", but this uuid is an attribute of Topology defiled in TapiTopology module. Should the Tapi:uuid be TapiTopology.uuid instead?

>             leaf _encapTopology {
                type leafref {
                    path '/Tapi:Context/Tapi:_topology/Tapi:uuid';
                }
                config false;
                description "none";
            }

Regards
Hui

**Comment by karthik-sethuraman** [comment]
I have assigned Ricard as he has tested this with the RI. But I believe the uuid/ID should be prefixed with the module where the list attribute appears. - in this case, the _topology is defined in the Tapi module under the Context.

**Comment by GermanoSMO** [comment]
Hi Hui

In a leafref, the XPath shall reflect the _resulting_ path, i.e. what will be the final position inside the resulting yang tree. The namespace will then be the one related to the module where the definitions are actually _used_ to define the instantiable tree. 

So, if you are using the attribute "uuid" as a child node of an instantiable tree belonging to the Tapi: namespace, it will assume that namespace, regardless where it was originally defined.

**Comment by HuiDingCATR** [comment]
Thanks Germano. In this case, although Topology is defined in TapiTopology, but it is instantiated in Tapi:Context, so it should be Tapi:uuid.

**Comment by rvilalta** [comment]
Agreed.
