### ISSUE TITLE
StatePac properties in the augmented Swagger modules do not contain the enum values

### ISSUE THREAD

**Issue by karthik-sethuraman** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#81]
#79 Found in the 1.0.0-RC1

[TapiTopology.swagger](https://github.com/OpenNetworkingFoundation/Snowmass-ONFOpenTransport/blob/develop/SWAGGER/TapiTopology.swagger)

        "AdminStatePac": {
            "description": "Provides state attributes that are applicable to an entity that can be administered. Such an entity also has operational and lifecycle aspects.",
            "properties": {
                "administrativeState": {
                    "type": "string",
                    "description": "none"
                },
                "operationalState": {
                    "type": "string",
                    "description": "none"
                },
                "lifecycleState": {
                    "type": "string",
                    "description": "none"
                }
            }
        },

[Tapi.swagger](https://github.com/OpenNetworkingFoundation/Snowmass-ONFOpenTransport/blob/develop/SWAGGER/Tapi.swagger)

        "AdminStatePac": {
            "description": "Provides state attributes that are applicable to an entity that can be administered. Such an entity also has operational and lifecycle aspects.",
            "properties": {
                "administrativeState": {
                    "enum": [
                        "LOCKED",
                        "UNLOCKED"
                    ],
                    "type": "string",
                    "description": "none"
                },
                "operationalState": {
                    "enum": [
                        "DISABLED",
                        "ENABLED"
                    ],
                    "type": "string",
                    "description": "none"
                },
                "lifecycleState": {
                    "enum": [
                        "PLANNED",
                        "POTENTIAL",
                        "INSTALLED",
                        "PENDING_REMOVAL"
                    ],
                    "type": "string",
                    "description": "none"
                }
            }
        },

**Comment by karthik-sethuraman** [comment]
This issue is found in AdminsStatePac, OperationalStatePac and LifecycleStatePac classes. These bugs appear in TapiTopology.swagger, TapiConnectivity.swagger, TapiPathComputation.swagger, TapiVirtualNetwork.swagger and TapiNotification.swagger.

**Comment by rvilalta** [comment]
Fixed in #82
