### ISSUE TITLE
Tapi.yang: Context class "instantiated" as a list statement

### ISSUE THREAD

**Issue by bzeuner** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#83]
Based on [https://github.com/OpenNetworkingFoundation/EAGLE-Open-Model-Profile-and-Tools/issues/142](url)

Hui:
 The TAPI Context class inherits from GlobalClass, which has the attribute uuid identified as "partOfObjectKey"; i.e., according to the Mapping Guidelines it should be mapped to "list Context". But according to UML, Context has only one instance so TAPI agreed it should be mapped to “container Context”.

Karthik:
 I don’t like the rule about inferring the root elements implicitly through key statements rather than explicitly via some "isRootList” or “isRootContainer" stereotype.
 It was noted that the root elements are not implicitly inferring through the key statement.

Bernd:
 We need to be careful not making the UML YANG dependent.

Potential solution:
 Don’t inherit Context from GlobalClass. Add a new uuid attribute directly to Context and don’t identify it as "partOfObjectKey"; i.e., flatten the inheritance by copying GlobalClass attributes directly into Context.

Karthik:
 I am fine with the proposed solution as a temporary workaround for the current mapping guideline limitation not as a proposed permanent solution. I do not want to start flipping class hierarchy based on the partOfObject key and list vs container mapping. Basically, I would like to define a key for most classes even if they are not currently used in a list somewhere, but has a potential to be used in future. The context is one such example. We may support multiple contexts and may even have a notion of user/tentant.

TAPI call Aug. 30:
The grouping Context will be manually “instantiated” as a container.

UML to YANG Mapping subteam call Aug. 31:
Keep the Mapping Guidelines and the Mapping Tool as is and always change the generated YANG for the root objects manually.

**Comment by rvilalta** [comment]
Fixed in #82
